# Generated by Django 5.0.6 on 2024-05-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('anons', models.CharField(max_length=250, verbose_name='Краткое содержание')),
                ('full_text', models.TextField(max_length=2500, verbose_name='Вся статья')),
                ('image', models.ImageField(upload_to='static', verbose_name='Картинка для публикации')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
