# Generated by Django 5.0.6 on 2024-05-14 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0002_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='dating',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
