# Generated by Django 5.0.6 on 2024-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0003_feedbacks_dating'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('aboutcompany', models.TextField(verbose_name='Рассказ о компании')),
                ('requisites', models.TextField(verbose_name='Реквизиты')),
                ('video', models.FileField(upload_to='static', verbose_name='Видео о компании')),
            ],
        ),
    ]
