# Generated by Django 5.0.6 on 2024-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0007_promocodes_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='work',
            field=models.BooleanField(default=True, verbose_name='Действует или в нет (в архиве)?'),
        ),
    ]
