# Generated by Django 5.0.6 on 2024-05-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0008_promocodes_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='dating',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
