# Generated by Django 5.0.6 on 2024-05-16 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0010_mebelspecies_seller_customer_mebel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='user',
        ),
        migrations.AddField(
            model_name='mebel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Заказчики', to=settings.AUTH_USER_MODEL),
        ),
    ]
