# Generated by Django 5.0.6 on 2024-05-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0011_remove_mebel_user_mebel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название точки')),
            ],
        ),
        migrations.AddField(
            model_name='mebel',
            name='buyCount',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Количество которое хотите купить'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default=0, max_length=20, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('deadline', models.DateField(verbose_name='Дата выполнения')),
                ('mebels', models.ManyToManyField(blank=True, related_name='z', to='furnfactshop.mebel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zakaz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
