# Generated by Django 5.0.6 on 2024-05-16 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0012_points_mebel_buycount_seller_name_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='mebels',
            field=models.ManyToManyField(blank=True, related_name='zakazi', to='furnfactshop.mebel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
