# Generated by Django 5.0.6 on 2024-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0013_remove_mebel_user_alter_order_mebels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='availableSellers',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=20, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=0, max_length=20, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
