# Generated by Django 5.0.6 on 2024-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0014_remove_customer_availablesellers_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default=0, max_length=20, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.CharField(default=0, max_length=20, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
