# Generated by Django 5.0.6 on 2024-05-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0015_seller_password_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='password',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
    ]
