# Generated by Django 5.0.6 on 2024-05-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0016_remove_customer_password_remove_customer_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='buyCount',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество объекта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnfactshop.seller')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furnfactshop.mebel')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='mebels',
            field=models.ManyToManyField(blank=True, related_name='zakazi', to='furnfactshop.orderobject'),
        ),
    ]
