# Generated by Django 5.0.6 on 2024-05-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0017_remove_mebel_buycount_alter_order_user_orderobject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='furnfactshop.seller'),
        ),
    ]
