# Generated by Django 5.0.6 on 2024-05-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0019_alter_orderobject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mebelnik', to='furnfactshop.mebel'),
        ),
    ]
