# Generated by Django 5.0.6 on 2024-05-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0020_alter_orderobject_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='furnfactshop.seller'),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mebelnik', to='furnfactshop.mebel'),
        ),
    ]
