# Generated by Django 5.0.6 on 2024-05-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0021_alter_orderobject_company_alter_orderobject_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество объекта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='furnfactshop.seller')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mebelnik', to='furnfactshop.mebel')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='mebels',
            field=models.ManyToManyField(blank=True, related_name='zakazi', to='furnfactshop.orderitem'),
        ),
        migrations.DeleteModel(
            name='OrderObject',
        ),
    ]
