# Generated by Django 5.0.6 on 2024-05-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0022_orderitem_alter_order_mebels_delete_orderobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='company',
        ),
        migrations.AddField(
            model_name='mebel',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='furnfactshop.seller'),
            preserve_default=False,
        ),
    ]
