# Generated by Django 5.0.6 on 2024-05-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0024_seller_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='furnfactshop.promocodes'),
            preserve_default=False,
        ),
    ]
