# Generated by Django 5.0.6 on 2024-05-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0025_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
