# Generated by Django 5.0.6 on 2024-05-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0027_alter_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='furnfactshop.seller'),
        ),
    ]
