# Generated by Django 5.0.6 on 2024-05-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0029_alter_mebel_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
    ]
