# Generated by Django 5.0.6 on 2024-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0032_customer_timezone_seller_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
