# Generated by Django 5.0.6 on 2024-05-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0034_remove_customer_timezone_customer_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='timezone',
        ),
    ]
