# Generated by Django 5.0.6 on 2024-05-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0036_mebel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='image',
        ),
    ]
