# Generated by Django 5.0.6 on 2024-05-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnfactshop', '0037_remove_mebel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='image',
            field=models.ImageField(default=0, upload_to='static', verbose_name='Картинка для публикации'),
            preserve_default=False,
        ),
    ]
